### ISSUE TITLE
UserProfileImage fails to load in production build

### ISSUE THREAD

**Issue by georgespano** [carbon-design-system/ibm-cloud-cognitive#1432]
UserProfileImage fails to load in production build: Using the UserProfileImage component in built app produces an error in the console (d.a.string.isRequired.if is not a function).

## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Using the UserProfileImage component produces an error in the console (d.a.string.isRequired.if is not a function). This happened only after upgrading @carbon/ibm-cloud-cognitive from 0.65.0 to 0.98.0. Note that this only happens after the component is part of a built app (npm run build). It does not produce this error on local build (npm start). See images below. Code where issue occurs was first introduced in https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1042 but version 0.65.0 (which I believe has the code) does not have the issue. I tried a number of versions and I believe it began failing roughly after version 0.75.0.

> Is this issue related to a specific component?
UserProfileImage component.

> What version of the @carbon/ibm-cloud-cognitive package are you using?
@carbon/ibm-cloud-cognitive 0.98.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Workflow Designer

## Steps to reproduce the issue

1. Use @carbon/ibm-cloud-cognitive 0.98.0 in package file
2. Use the UserProfileImage component
3. Build the page (npm run build) and deploy it. Page will fail to load: (d.a.string.isRequired.if is not a function)

![image](https://user-images.githubusercontent.com/94184224/141487990-1e0713eb-8c8c-47ca-a2c7-c220f1c7b78f.png)
![image](https://user-images.githubusercontent.com/94184224/141488027-9a0bdd19-0991-45c3-b3fa-2330078f1bb9.png)
